### ISSUE TITLE
lichess-bot stops sending or accepting challenges

### ISSUE THREAD

**Issue by JimViebke** [lichess-bot-devs/lichess-bot#1003]
**Describe the bug**

lichess-bot often sits idle after a game, without creating a challenge or acknowledging most of the incoming challenges (restarting the script manually seems to temporarily resolve this).

The timeline, per the attached [recent.log](https://github.com/user-attachments/files/16537069/recent.log):
- At 20:53:02, lichess-bot challenges blank_bot to a game. blank_bot accepts and the game is played.
- At 21:20:07, the game finishes, and lichess-bot says "Next challenge will be created after 21:21:07". I don't think it ever creates a challenge.
- At 21:31:54, lichess-bot receives a challenge from daddyshark_bot, and appears to ignore it (I think it should have accepted the challenge per the config file). This challenge does not show up in the logs again, so it is unclear if the challenge was ever cancelled.
- At 21:38:49, lichess-bot receives a challenge from chessxbot, and appears to ignore it (again, I think it should have been accepted per the config). The opponent cancels the challenge about half a minute later.
- At 22:30:45, lichess-bot receives a challenge from nakshatra3, and correctly declines it for being unrated.
- At 22:50:55, lichess-bot receives a challenge from chessxbot. As above, it appears this challenge is ignored, and the opponent cancels the challenge about half a minute later.

**To Reproduce**
1. Run lichess-bot 2024.8.6.1 with `venv\Scripts\activate` and `py lichess-bot.py -v`, and the config as specified in the attached log.

**Desktop:**
 - OS: Windows 10
 - Python Version: 3.12
 - Terminal: Windows PowerShell

(I'm not sure if this is related to my previous issue, #991. That thread links to a couple of issues and commits that could be relevant.)

**Comment by AttackingOrDefending** [comment]
Setting `challenge.concurrency` to 1 should fix the problem. Matchmaking with `challenge.concurrency = 0` has some weird properties.

How the problem was caused:
Since you have  `challenge.concurrency = 0` your bot won't accept any challenge from other players, and your [`max_games`](https://github.com/lichess-bot-devs/lichess-bot/blob/master/lichess-bot.py#L336) will be set to 0. Then [`max_games_for_matchmaking`](https://github.com/lichess-bot-devs/lichess-bot/blob/master/lib/matchmaking.py#L256) will be set to 1. Your [`game_count`](https://github.com/lichess-bot-devs/lichess-bot/blob/master/lib/matchmaking.py#L257) was initially 0 because your bot hadn't been challenged, so the matchmaker challenged other bots. After your bot received challenges, `game_count` became larger than 0, so your bot stopped challenging because [`game_count >= max_games_for_matchmaking`](https://github.com/lichess-bot-devs/lichess-bot/blob/master/lib/matchmaking.py#L258).

**Comment by AttackingOrDefending** [comment]
Can you try #1004? If you try #1004 without changing `concurrency` then your bot shouldn't create any challenge. If you change `concurrency` to 1, then #1004 won't make any difference.

**Comment by JimViebke** [comment]
Thanks for the explanation, and the fix. I'll try #1004 tomorrow.

**Comment by JimViebke** [comment]
On #1004, lichess-bot correctly creates a challenge when concurrency is set to 1, and does not create a challenge when concurrency is 0. The issue appears resolved, thanks!

Should I leave this issue open until #1004 is merged?

**Comment by AttackingOrDefending** [comment]
You can close it now if you want.
