### ISSUE TITLE
Let Homemade Engines Communicate via Chat

### ISSUE THREAD

**Issue by Others** [lichess-bot-devs/lichess-bot#1007]
Unless I'm missing something, it's not currently possible to have a homemade engine read or write chat messages during games. (At least not without hacking around current abstractions.)

When developing my bot, it would be super helpful to be able to write a diagnostic message into chat in some exceptional situations. So I'm primarily interested in being able to type unilaterally during the "search" call.

I think I can probably accomplish what I want by just hacking on the code a little bit myself, but I'm wondering if it would be in scope for this to be properly supported by the project.

**Comment by MarkZH** [comment]
Communication by chat is very limited for all engine types (XBoard, UCI, and homemade) since lichess looks down on automated posting. The currently allowed messages are:
- Hello/goodbye as defined in the [user's config file](https://github.com/lichess-bot-devs/lichess-bot/blob/9fbd2861007885a18867e416e7313835b332fe0a/config.yml.default#L170-L178).
- Responses to `!commands` as seen in [conversation.py](https://github.com/lichess-bot-devs/lichess-bot/blob/9fbd2861007885a18867e416e7313835b332fe0a/lib/conversation.py#L71-L91). None of these allow for posting arbitrary text.

If you need diagnostic messages from your engine, is there a reason that the log files aren't sufficient?

**Comment by AttackingOrDefending** [comment]
Communicating during the search isn't possible currently as lichess-bot is synchronous. So it would require quite a few changes to implement.

> Also my bot has some edge cases where it might play a bit odd (specific to my usecase) and I'd love to be able to tell the opponent something has gone a bit wrong.

After, the [search](https://github.com/lichess-bot-devs/lichess-bot/blob/master/lichess-bot.py#L710) you can send a message to the user if it played a bit odd.
```
engine.play_move(board, game, li, setup_timer, move_overhead, can_ponder, is_correspondence, correspondence_move_time, engine_cfg, fake_think_time(config, board, game))
if engine.played_odd:
    conversation.send_reply(ChatLine({"room": "player", "username": "", "text": ""}), "The engine played an odd move.")
time.sleep(to_seconds(delay))
```
The code isn't the cleanest but it may be good enough for your use case.

> Is this an official policy that you can cite from somewhere? I don't see documentation in the API reference.

The code for the chat is [here](https://github.com/lichess-org/lila/blob/master/modules/chat/src/main/ChatApi.scala#L239) where you can also probobaly find the restrictions. In [this issue](https://github.com/lichess-org/lila/issues/12538) the user mentions that when sending suplicate messages one should wait (the issue was from the point of the human player, but the same rules still apply).

> Would it be reasonable to let homemade engines add new commands? That would at least get me somewhat to where I want
p.s. I'm happy to contribute code for these suggested features, I just want to make sure you want the PR before I spend time on it :)

Some changes to make it simpler to add custom chat messages, like the one shown above, are good. I would accept a PR allowing engines to talk during games, provided it doesn't use some hacky methods (so probably no `threading`), but most desirable would be to allow this for all engine types (not only homemade) (e.g. see [here](https://www.gnu.org/software/xboard/engine-intf.html) the section about `tellopponent MESSAGE`, `tellothers MESSAGE` and `tellall MESSAGE`) (uci engines don't have that ability, adding a lichess-bot specific `info string chat MESSAGE_HERE` may be a bit to much).

**Comment by MarkZH** [comment]
The difficulty with using XBoard chat commands (`tellopponent`, etc.) is that python-chess doesn't support them. I just tried having my engine output `tellall Good game!` and python-chess printed the warning `Unexpected engine output: 'tellall Good game!'`. That library would have to be updated prior to this feature.

**Comment by MarkZH** [comment]
Since it seems like this feature would not be used by most players, I'm closing this issue. @Others, if you would like help while implementing this chat feature (@AttackingOrDefending's idea above seems a good way to go about it) feel free to reply here or [start a discussion](https://github.com/lichess-bot-devs/lichess-bot/discussions).
