### ISSUE TITLE
clock and inc are always NoneType

### ISSUE THREAD

**Issue by JadenSchalck** [lichess-bot-devs/lichess-bot#1025]
**Describe the bug**
I am making a bot in homemade.py. I tried to use the `white_clock`, `black_clock`, `white_inc`, and `black_inc` variables from the `Limit` class. They appear to always be NoneType and never int.
I may just not understand how they work. I could not find a good example on how to use them.

**To Reproduce**
1. In `homemade.py`, create a class that inherits `MinimalEngine` and has a search function that takes a `Limit` argument.
2. In `config.yml`, set name to the name of your class (Metropolis-Chess in my case) and protocol to "homemade".
3. Inside the search function, use `white_clock`, `black_clock`, `white_inc`, or `black_inc`. (`timeLimit.black_clock` in my case)
5. Run lichess-bot with [`py -3 lichess-bot.py -u`] commands.
6. See error

**Expected behavior**
`white_clock`, `black_clock`, `white_inc`, and `black_inc` are ints and not NoneType

**Logs**
`lichess_bot_auto_logs\recent.log`
[recent.log](https://github.com/user-attachments/files/17158349/recent.log)
`lichess_bot_auto_logs\old.log`
[old.log](https://github.com/user-attachments/files/17158350/old.log)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Python Version: 3.12.6 64-bit
 - Terminal: Command Prompt

I can also include the entirety of my bot's code if needed.

**Comment by MarkZH** [comment]
The error occurs because of this line:
```python
if timeLimit.black_clock >= 30:
```
For the first move of the game, only `timeLimit.time` will have a value that is not `None`. This field indicates how much time to use just for this move. This is because Lichess uses a constant time limit for the first move. The usual game clocks (`wtime`, `winc`, etc.) start after the first move.

If you want your bot to play correspondence games, it will have to read `timeLimit.time` there, as well.

**Comment by JadenSchalck** [comment]
Thanks for letting me know. I thought the Lichess auto abort was a separate timer. I have got it working now.
