### ISSUE TITLE
Bot suddenly stopped accepting challenges

### ISSUE THREAD

**Issue by SebLague** [lichess-bot-devs/lichess-bot#748]
Hello, and thanks for this amazing repo!

I've been running a bot for over a week now without any issues, until this morning it (seemingly randomly) stopped accepting challenges. I've tried restarting, but it still doesn't work.

I'm running the bot with the command 'python3 lichess-bot.py -v', at which point the welcome message shows in the console stating that the bot is connected to lichess (and it appear online on the website too). However, if I then challenge the bot on lichess, nothing happens. On lichess it just says 'Waiting for opponent', and in Command Prompt there is no indication of the challenge having been received.

Additionally, when the bot is seeking for matches against other bots, the log looks like this:

```
INFO     Will challenge Shineshou90_BOT for a standard game.                               matchmaking.py:202
DEBUG    https://lichess.org:443 "POST /api/challenge/Shineshou90_BOT HTTP/1.1" 200     connectionpool.py:452
None
INFO     Challenge id is 3F11Q4Ki.                                                         matchmaking.py:204
DEBUG    Resetting dropped connection: lichess.org                                      connectionpool.py:272
DEBUG    https://lichess.org:443 "POST /api/challenge/3F11Q4Ki/cancel HTTP/1.1" 200 11  connectionpool.py:452
INFO     Challenge id 3F11Q4Ki cancelled.                                                   matchmaking.py:69

```
I am on windows 10 using python 3.9.13
Any suggestions as to what the issue might be, or how I could go about trouble-shooting it would be greatly appreciated!

**Comment by chrinspire** [comment]
I'm having the same symptom:
I can either create a now token with only one permission: 'bot:play' - then it logs on, but no challenges work (obviously, because of the missing challange rights). -> log looks like yours then.

But:
If I create+use a token with 'challenge:read'+write, it cannot even log in any more. The log then says: 
` RuntimeError: Please use an API access token for your bot
that has the scope "Play games with the bot API (bot:play)".
The current token has: ['challenge:read', '
challenge:write', ' bot:play'].`
looking carefully there is a blank between the apostroph and the '_bot:play'. 
There seems to be a bug in token creation or comparison that makes it not accept the token as a bot-play token.
Only the first permission does not have the blank. That could explain why the token with the single bot:play permission is accepted...

**Comment by MarkZH** [comment]
First, please upgrade to the latest version of lichess-bot. Then, run lichess-bot again until the error happens (when it becomes obvious that challenges are not being accepted). Detailed logs will be created in a folder called `lichess_bot_auto_logs`. Post those files here.

@chrinspire Upgrading will fix your error regarding the token scopes.

**Comment by SebLague** [comment]
Thanks for the response @MarkZH Strangely, it seems to be working fine again this morning. No idea why! I've attached the log file from yesterday in case it's helpful, although it also doesn't seem to show any record of receiving a challenge (I did try sending it multiple challenges during that time).

[old.log](https://github.com/lichess-bot-devs/lichess-bot/files/11830232/old.log)

**Comment by MarkZH** [comment]
It's possible it was a temporary glitch with lichess.org. But, it's great that everything's working. Feel free to reopen this issue if the problem comes up again.

**Comment by MarkZH** [comment]
I saw other people report similar problems elsewhere, so it wasn't just you.
