### ISSUE TITLE
Issues with UCI communication

### ISSUE THREAD

**Issue by sscg13** [lichess-bot-devs/lichess-bot#768]
**Describe the bug**
Lichess-bot raises a TimeoutError when working with engine even though the engine is expected to support all UCI commands used.

**To Reproduce**
1. Run lichess-bot with https://github.com/sscg13/sscg13-chess-engine (need C++23 support to compile)
2. See error

**Expected behavior**
Games would be played normally, as would happen with Stockfish or Komodo

**Logs**
[old.log](https://github.com/lichess-bot-devs/lichess-bot/files/11938790/old.log)

**Desktop (please complete the following information):**
 - OS: Windows
 - Python Version 3.11

**Comment by AttackingOrDefending** [comment]
The problem is the space after `uciok` in [line 1378](https://github.com/sscg13/sscg13-chess-engine/blob/main/Board.cpp#L1378) of your engine. [python-chess](https://github.com/niklasf/python-chess/blob/v1.9.4/chess/engine.py#L1358) checks for an exact match to `uciok`. There is an [open issue about whitespace](https://github.com/niklasf/python-chess/issues/970).

**Comment by sscg13** [comment]
Deleting the whitespace fixed the issue, thanks!
