### ISSUE TITLE
Make matchmaking time delay shorter

### ISSUE THREAD

**Issue by FatFritz2** [lichess-bot-devs/lichess-bot#840]
Hi 
Can I suggest you guys to make the matchmaking_time_delay in config.yml to 0.1 minute (10 seconds) to make the bot challenge more opponent 
P/S: can you make matchmaking better by searching from the highest elo to lower elo opponents

**Comment by FatFritz2** [comment]
Yorry, I mean reducing it to arround 0,16 min to 0,25 min (10 seconds to around 25seconds)
To be honest Torom's Botli also support the matchmaking delay option down to 10 seconds
In fact i suggest you use seconds not minutes for the matchmaking_time option here

**Comment by MarkZH** [comment]
Lichess limits API users to 400 challenges a day (this could be raised or lowered in the future). That's an average of one every 3.6 minutes. Since faster games are more popular, lowering the delay between matchmaking challenges will only cause rate-limiting 429 errors to happen more quickly. This would cause lichess-bot users to spend up to half of every day unable to challenge opponents while waiting for the daily challenge limit to expire. We won't be making this change.

We will consider the matchmaking change.

**Comment by AttackingOrDefending** [comment]
Also, if we were to change the delay from minutes to seconds, we would have a problem with backwards compatibility.

The problem with the matchmaking change would be that the bot would play the same bot often, which can lead to more declined challenges (because of `max_recent_bot_challenges`). I think the new `selection` parameter would have to take 5 values: `random`, `highest`, `lowest`, `weighted_highest` and `weighted_lowest`. `weighted_highest` and `weighted_lowest` would work like `weighted_random` in opening books. This way the bot will prefer higher rated opponents but will have a higher variance. The downside to `weighted_highest` is that we would have to come up with a function to give a weight to each bot.

**Comment by FatFritz2** [comment]
Hey, in the !eval command, I dont see where is hash info located
And how can I enable hash infos ? Or if you havent got that feature ?
Thanks

**Comment by FatFritz2** [comment]
I've already replaced your code there but it seems not showing: `Evaluation: 3.6, Winrate: 100.0%, Depth: 34, Nodes: 22.8M, Speed: 2.0Mnps, Pv: ...`

**Comment by AttackingOrDefending** [comment]
Sorry. It is `Hashfull` and not `Hash`. `stats = ["Source", "Evaluation", "Winrate", "Depth", "Nodes", "Speed", "Hashfull", "Pv"]` should work.
