### ISSUE TITLE
Engine isn't closed properly on invalid options

### ISSUE THREAD

**Issue by AttackingOrDefending** [lichess-bot-devs/lichess-bot#903]
**Describe the bug**
If we find a problem while running the initial check to see if the engine supports the options provided by the user, we raise an error but lichess-bot hangs instead of closing. I had to press Ctrl+C for the engine to close, which is why there is a 13 seconds delay in the log file.

My guess is that it is caused by [this line](https://github.com/lichess-bot-devs/lichess-bot/blob/master/lib/engine_wrapper.py#L108).

**To Reproduce**
1. Add `Hash2: 2` to `uci_options`
2. Run lichess-bot using Stockfish
3. See error

**Expected behavior**
lichess-bot terminates properly instead of hanging.

**Logs**
[recent.log](https://github.com/lichess-bot-devs/lichess-bot/files/14151366/recent.log)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.12

**Additional context**
None

**Comment by MarkZH** [comment]
It seems the problem is that the line you highlighted is never reached. Since the engine class `__init__()` methods never complete due to the exception raised by `self.engine.configure()`. This means that the `__enter__()` method called by `with` never completes, which prevents `__exit__()` from being called. So, the connection to the engine is never closed.
