### ISSUE TITLE
lichess-bot issues new challenges before cancelling old ones, allowing too many concurrent games, which time out

### ISSUE THREAD

**Issue by JimViebke** [lichess-bot-devs/lichess-bot#991]
**Describe the bug**

lichess-bot seems to issue new challenges before cancelling old ones. This allows one opponent to accept a newer challenge, starting a game. While this game is in progress, another opponent can accept the older challenge, creating a second game that appears to be (correctly) ignored by lichess-bot. While the existing game is played, the new game eventually times out and is aborted.

Observed behavior: lichess-bot allows more games to start than it will play.
Expected behavior: lichess-bot limits open challenges to `concurrency + 1`.

config.yml currently has `concurrency: 0` and `allow_during_games: false`.

(side suggestion: in future configs, change:
`concurrency: 0   # Number of games to play simultaneously.`  
to:
`concurrency: 1   # Maximum number of games to play at once. The min is 1.`)

The timeline, per recent.log (attached):
- 18:53: lichess-bot challenges ai-con (game `osCQjeIm`).
- 18:54: lichess-bot challenges StockSquidV2 (game `5Sz1P70f`). The game starts at 18:54 and completes at 19:00.
- 19:01: lichess-bot challenges The_Marcus (game `CdRG6Obm`).
- 19:01: Game with The_Marcus starts.
- 19:02: Game with ai-con starts.
- 19:03: Game with ai-con times out per `abort_time: 30` in config.yaml (["Game aborted" on lichess.org](https://lichess.org/osCQjeIm2zL5)).
- 19:06: Game with The_Marcus completes.
- 19:06: lichess-bot prepares to play the game with ai-con, and notices that it has aborted.

It may be a separate issue, but lichess-bot seems to stop receiving or accepting challenges at this point, and just idles until it is restarted.

**Logs**
[recent.log](https://github.com/user-attachments/files/16322600/recent.log)

**Desktop:**
 - OS: Windows 10
 - Python Version: Python 3.12.4
 - Terminal: PowerShell (using `venv\Scripts\activate`, `py lichess-bot.py`)

**Comment by MarkZH** [comment]
I think both issues are related to the `ERROR` lines in your logs. Due to a change in the response format from Lichess to challenges, the game ID of the matchmaking challenge is not being extracted correctly. This has two effects:

1. The challenge cannot be cancelled because there's no record of the game id--hence why the game with ai-con started nine minutes after the challenge was sent.
2. Every bot that gets challenged gets put on a block list because challenging them resulted in an error. So lichess-bot eventually stops challenging any bots since they are all on a block list.

I've filed [an issue](https://github.com/lichess-org/api/issues/361) with the Lichess developers. Let's see if fixing that fixes this.

**Comment by MarkZH** [comment]
I've created a PR (#992) to address this issue. Please try it and let me know if it fixes the problem.

**Comment by MarkZH** [comment]
Please reopen if this issue persists.
